name: Build and Deploy Spring Boot WAR

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload WAR file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.NAME_APP }}-war
          path: target/${{ env.NAME_APP }}-1.0.1.war
      
      - name: List target directory contents
        run: ls -l target

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.NAME_APP }}-war

      - name: List target directory contents
        run: ls -l ./

      - name: Rename WAR file
        run: mv ${{ env.NAME_APP }}-1.0.1.war ${{ env.NAME_APP }}.war

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH Key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Debug SSH Agent
        run: ssh-add -l

      - name: Upload WAR to server
        run: scp -v ${{ env.NAME_APP }}.war ubuntu@${{ secrets.SERVER_IP }}:/opt/tomcat/webapps/


  test:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Wait for Service to Start
        run: sleep 3

      - name: Test GET all values
        run: curl -f --location 'https://${{ secrets.SERVER_IP }}:8443/${{ env.NAME_APP }}/api/v1' --insecure

      - name: Test GET specific value
        run: curl -f --location 'https://${{ secrets.SERVER_IP }}:8443/${{ env.NAME_APP }}/api/v1/1' --insecure

      - name: Test POST values
        run: |
          curl -f --location --request POST "https://${{ secrets.SERVER_IP }}:8443/${{ env.NAME_APP }}/api/v1" \
          --data 'Chile' \
          --insecure \
          --header 'Content-Type: text/plain'
      
      - name: Test PUT values
        run: |
          curl -f --location --request PUT 'https://${{ secrets.SERVER_IP }}:8443/${{ env.NAME_APP }}/api/v1/6' \
          --header 'Content-Type: text/plain' \
          --data 'Marruecos' \
          --insecure

      - name: Test DELETE values
        run: curl -f --location --request DELETE 'https://${{ secrets.SERVER_IP }}:8443/${{ env.NAME_APP }}/api/v1/6' --insecure
